export enum EnvVariables {
  PORT = "PORT",
  NODE_ENV = "NODE_ENV",
  THROTTLE_LIMIT = "THROTTLE_LIMIT",
  THROTTLE_TTL = "THROTTLE_TTL",

  DATABASE_URI = "DATABASE_URI",

  SENDER_ID = "SENDER_ID",
  SENDER_PASSWORD = "SENDER_PASSWORD",
  EMAIL_SECRET = "EMAIL_SECRET",

  ONESIGNAL_USER_API_KEY = "ONESIGNAL_USER_API_KEY",
  ONESIGNAL_USER_APP_ID = "ONESIGNAL_USER_APP_ID",

  ONESIGNAL_DELIVERY_PARTNER_API_KEY = "ONESIGNAL_DELIVERY_PARTNER_API_KEY",
  ONESIGNAL_DELIVERY_PARTNER_APP_ID = "ONESIGNAL_DELIVERY_PARTNER_APP_ID",

  ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET",
  REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET",
  ACCESS_TOKEN_EXPIRATION = "ACCESS_TOKEN_EXPIRATION",
  REFRESH_TOKEN_EXPIRATION = "REFRESH_TOKEN_EXPIRATION",
  PUBLIC_KEY = "PUBLIC_KEY",
  PRIVATE_KEY = "PRIVATE_KEY",

  TWILIO_SENDER_NUMBER = "TWILIO_SENDER_NUMBER",
  TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID",
  TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN",

  REDIS_HOST = "REDIS_HOST",
  REDIS_PASSWORD = "REDIS_PASSWORD",
  REDIS_PORT = "REDIS_PORT",

  STRIPE_SECRET = "STRIPE_SECRET",
  STRIPE_WEBHOOK_SECRET = "STRIPE_WEBHOOK_SECRET",
}
