export enum OrderNotificationStatus {
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  ORDER_ACCEPTED_BY_DELIVERY_BOY = "ORDER_ACCEPTED_BY_DELIVERY_BOY",
  ORDER_REJECTED_BY_DELIVERY_BOY = "ORDER_REJECTED_BY_DELIVERY_BOY",
  PRODUCT_OUT_OF_STOCK = '"PRODUCT_OUT_OF_STOCK"',
  ORDER_ON_ROAD = "ORDER_ON_ROAD",
  ORDER_DELIVERED = "ORDER_DELIVERED",
}
